### ISSUE TITLE
登录优化

### ISSUE THREAD

**Issue by barry200890** [YangZxi/Cloud#1]
希望增加用户登录验证码，可以使用漂亮的easycaptcha

**Comment by YangZxi** [comment]
感谢你对此项目的关注
这个问题我想过，但是不在目前的 Todo 计划当中，因为此项目是没有开放注册功能的，换言之只有网站所有者手在后台手动创建账号，用户的范围被限制在了站长的好友圈子内
后期会为带密码的分享链接加入验证码功能

**Comment by barry200890** [comment]
哦哦，可以的
