### ISSUE TITLE
redisCache代码有问题哦

### ISSUE THREAD

**Issue by barry200890** [YangZxi/cloud#2]
![image](https://github.com/YangZxi/Cloud/assets/65383345/76bf5106-7d14-4692-9ab4-b641926d3602)

**Comment by YangZxi** [comment]
这是 jdk14 的新特性 record ，运行源代码请使用 jdk17+ 的开发环境

**Comment by barry200890** [comment]
idea2019版本的选择了jdk用17，但是编译这块最高只能选这个x-expermental这个：
![image](https://github.com/YangZxi/Cloud/assets/65383345/9cbc2ea6-17ac-49d2-bee1-afe1b2105f90)

是只能升级idea版本了么？

**Comment by YangZxi** [comment]
是的，建议升级到 2021.3 或者最新版

**Comment by barry200890** [comment]
恩，用2023.1版本的可以运行了。
