### ISSUE TITLE
sql里语句不完整

### ISSUE THREAD

**Issue by barry200890** [YangZxi/cloud#3]
菜单表里的数据缺失。。

**Comment by YangZxi** [comment]
先执行一下根目录的 sql 语句，启动项目的时候会自动创建数据

**Comment by barry200890** [comment]
哦，导入编译的时候不知道为啥gradle报这个错。感觉gradle还是没maven好用

**Comment by barry200890** [comment]
![image](https://github.com/YangZxi/Cloud/assets/65383345/906632ab-e7ba-4f3a-88bb-aa3f82d55232)

**Comment by YangZxi** [comment]
已修复

**Comment by barry200890** [comment]
gradle的报错看不来，不像maven的报错一看就知道是咋回事了

**Comment by barry200890** [comment]
不行，刚才pull下最新的代码，刷新的gradle，但还是有报错
![image](https://github.com/YangZxi/cloud/assets/65383345/f3620c6a-9202-448c-8582-0fbbe255508c)

**Comment by YangZxi** [comment]
file > project structure，把项目名称改为 cloud 小写，或者重新 clone 项目不是 pull

**Comment by barry200890** [comment]
恩，可以了，后台终于跑起来了

**Comment by barry200890** [comment]
![image](https://github.com/YangZxi/cloud/assets/65383345/99ab418b-41a6-4171-9a31-daa59d20a11a)
前端install的时候怎么报错呢

**Comment by YangZxi** [comment]
使用 pnpm 试试

**Comment by barry200890** [comment]
恩，我刚用yarn命令好使了

**Comment by barry200890** [comment]
发现还是得用pnpm比较好用，用yarn安装的话，会少几个依赖。换了pnpm可以运行起来前端了
